# Generated by Django 5.0.6 on 2024-05-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
