# Generated by Django 5.0.3 on 2024-03-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default="defalutl='취미;", max_length=50),
            preserve_default=False,
        ),
    ]
